---
spring:
  application:
    name: s3-examples
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
        sts:
          role-arn: ${AWS_ROLE_ARN}
          role-session-name: ${AWS_ROLE_SESSION_NAME}
      region:
        static: ap-northeast-1
      s3:
        endpoint: http://127.0.0.1:9000
        bucket: sandbox-bucket

logging:
  level:
    jp:
      kukv: debug

batch:
  tmp-dir: build/tmp/
